twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: [ 'forms_layout/tailwind_form_layout.html.twig' ]

    globals:
        SITE_NAME: '%env(SITE_NAME)%'

when@test:
    twig:
        strict_variables: true
